// <auto-generated />
using DrawItFaster.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrawItFasterGame.Migrations
{
    [DbContext(typeof(DrawItDbContext))]
    [Migration("20260527104401_SeedWords")]
    partial class SeedWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrawItFaster.Models.Word", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordID"));

                    b.Property<string>("WordString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordID");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            WordID = 1,
                            WordString = "Apple"
                        },
                        new
                        {
                            WordID = 2,
                            WordString = "Car"
                        },
                        new
                        {
                            WordID = 3,
                            WordString = "Dog"
                        },
                        new
                        {
                            WordID = 4,
                            WordString = "Cat"
                        },
                        new
                        {
                            WordID = 5,
                            WordString = "House"
                        },
                        new
                        {
                            WordID = 6,
                            WordString = "Sun"
                        },
                        new
                        {
                            WordID = 7,
                            WordString = "Tree"
                        },
                        new
                        {
                            WordID = 8,
                            WordString = "Computer"
                        },
                        new
                        {
                            WordID = 9,
                            WordString = "Coffee"
                        },
                        new
                        {
                            WordID = 10,
                            WordString = "Bike"
                        });
                });

            modelBuilder.Entity("DrawItFasterGame.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("Highscore")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rankscore")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
